kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-operator-manager-role
  uid: 092c1ea0-4835-44c5-b65b-ff5d1fb7c6e1
  resourceVersion: '10099'
  creationTimestamp: '2023-05-11T10:29:23Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"creationTimestamp":null,"name":"gitops-operator-manager-role"},"rules":[{"apiGroups":[""],"resources":["configmaps","endpoints","events","persistentvolumeclaims","pods","secrets","serviceaccounts","services","services/finalizers"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resources":["namespaces","resourcequotas"],"verbs":["create","delete","get","list","update","watch"]},{"apiGroups":[""],"resources":["pods/log"],"verbs":["get"]},{"apiGroups":["apps"],"resources":["daemonsets","deployments","replicasets","statefulsets"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"resourceNames":["gitops-operator"],"resources":["deployments/finalizers"],"verbs":["update"]},{"apiGroups":["apps.openshift.io"],"resources":["*"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["argoproj.io"],"resources":["applications","appprojects","argocds","argocds/finalizers","argocds/status"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["autoscaling"],"resources":["horizontalpodautoscalers"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["batch"],"resources":["cronjobs","jobs"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["config.openshift.io"],"resources":["clusterversions"],"verbs":["get","list","watch"]},{"apiGroups":["console.openshift.io"],"resources":["consoleclidownloads"],"verbs":["create","get","list","patch","update","watch"]},{"apiGroups":["console.openshift.io"],"resources":["consolelinks"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["console.openshift.io"],"resources":["consoleplugins"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["monitoring.coreos.com"],"resources":["prometheuses","prometheusrules","servicemonitors"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["networking.k8s.io"],"resources":["ingresses"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["oauth.openshift.io"],"resources":["oauthclients"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["operators.coreos.com"],"resources":["clusterserviceversions","operatorgroups","subscriptions"],"verbs":["create","get","list","watch"]},{"apiGroups":["pipelines.openshift.io"],"resources":["*"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["pipelines.openshift.io"],"resources":["gitopsservices"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["pipelines.openshift.io"],"resources":["gitopsservices/finalizers"],"verbs":["update"]},{"apiGroups":["pipelines.openshift.io"],"resources":["gitopsservices/status"],"verbs":["get","patch","update"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["*"],"verbs":["bind","create","delete","deletecollection","escalate","get","list","patch","update","watch"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["clusterrolebindings","clusterroles"],"verbs":["bind","create","delete","deletecollection","escalate","get","list","patch","update","watch"]},{"apiGroups":["route.openshift.io"],"resources":["*"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["route.openshift.io"],"resources":["routes","routes/custom-host"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["template.openshift.io"],"resources":["templateconfigs","templateinstances","templates"],"verbs":["create","delete","get","list","patch","update","watch"]}]}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2023-05-11T10:29:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:rules': {}
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
      - services/finalizers
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
      - resourcequotas
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - update
    apiGroups:
      - apps
    resources:
      - deployments/finalizers
    resourceNames:
      - gitops-operator
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps.openshift.io
    resources:
      - '*'
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
      - argocds
      - argocds/finalizers
      - argocds/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
  - verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consoleclidownloads
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consoleplugins
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
      - prometheusrules
      - servicemonitors
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - operatorgroups
      - subscriptions
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - pipelines.openshift.io
    resources:
      - '*'
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - pipelines.openshift.io
    resources:
      - gitopsservices
  - verbs:
      - update
    apiGroups:
      - pipelines.openshift.io
    resources:
      - gitopsservices/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - pipelines.openshift.io
    resources:
      - gitopsservices/status
  - verbs:
      - bind
      - create
      - delete
      - deletecollection
      - escalate
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - '*'
  - verbs:
      - bind
      - create
      - delete
      - deletecollection
      - escalate
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - '*'
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - template.openshift.io
    resources:
      - templateconfigs
      - templateinstances
      - templates
